### ISSUE TITLE
Create a banner that shows Solana TPS as well as a warning when TPS is low

### ISSUE THREAD

**Issue by BowTiedHeron** [honey-labs/honey-frontend#150]
See magic eden as an example:

![Image](https://user-images.githubusercontent.com/93859808/174305065-b3ab66e2-c6a8-42f6-885f-5cc82b60d74b.png)

Probably already built by someone opensource.
TPS = Transactions Per Second

**Comment by FlacoJones** [comment]
A bounty has been minted for this issue at https://app.openq.dev/bounty/I_kwDOHB1JPc5L_zuL/0xF48578DF83229BD29148AF888B675Db5e870196F

**Comment by eborrallo** [comment]
Opened PR: https://github.com/honey-labs/honey-frontend/pull/162

Also i have a question:
https://app.openq.dev/bounty/I_kwDOHB1JPc5L_zuL/0xf48578df83229bd29148af888b675db5e870196f

What does it means "warning when TPS is low" ,i mean  low is under what number or low compared with what ?
For me "low" is an ambiguous word, please can you specify ?

**Comment by tomjpandolfi** [comment]
Hey good question.

Low TPS will be set at 1700 TPS to err on the side of caution.
