### ISSUE TITLE
UI is breaking for S8+ and lower-dimensions

### ISSUE THREAD

**Issue by Sam44323** [honey-labs/honey-frontend#187]
**Describe the bug**
UI is breaking for the mobile viewports with issues such as overflowing/contractions

**To Reproduce**

Use chrome dev-tools and with dimensions add 360 X 740

1. Go to Chrom Dev Tools
2. Click on Add 360 X 740 in dimensions
3. See an error

**Expected behavior**
PFA a screen-shot of the issue
<img width="345" alt="Screenshot 2022-09-29 at 10 42 54 PM" src="https://user-images.githubusercontent.com/65643151/193096876-3b21dfa5-169d-4a68-afc2-52b5c92a5503.png">

**Comment by BowTiedHeron** [comment]
@Sam44323 sorry for not getting back to you sooner, your effort is much appreciated!
we are working on a complete redesign of the dapp and will integrate mobile optimisations there!
