### ISSUE TITLE
General - Clearer difference between clickable buttons vs non-clickable buttons

### ISSUE THREAD

**Issue by GHesericsu** [honey-labs/honey-frontend#59]
**Governance** looks like the same disabled button as **Dashboard** and **Loans**

If we want people to use **Governance**, we should make it clear that it's clickable. 

If we want people to know **Dashboard** and **Loans** are coming soon but not clickable then label it as such( coming soon...) label. Don't fool users. 

**Additional context (optional)**
Add any other context or screenshots about the feature request here
<img width="278" alt="Screen Shot 2022-04-05 at 4 07 09 PM" src="https://user-images.githubusercontent.com/60202455/161788046-1bc1fcb3-a3be-407a-860a-b3c3c3c96a4c.png">
.

**Comment by BowTiedHeron** [comment]
<img width="284" alt="image" src="https://user-images.githubusercontent.com/93859808/162625711-934b32fa-1585-42f4-b76f-b82131c4a4d1.png">

just saw this; might be a nice solution

**Comment by GHesericsu** [comment]
nice

**Comment by tomdreamevil** [comment]
I would say not to overlap the labels though, I would place the "beta" message on the right of the button or snap underneath when at a breakpoint. Thoughts?
